# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest


    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - run: npm run --prefix ./UI
    - run: npm build --prefix ./UI    
    - name: Configure AWS credentials from Test account
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    
    
    - name: Build Docker container
      run: docker build -t prasanna002/nodejs --file ./UI/Dockerfile .
    - run: docker login -u ${{ secrets.DOCKER_USER }} 
             -p ${{ secrets.DOCKER_PASS }}
    - run: docker push prasanna002/nodejs
      
    - name: deploy  to ECS
      run: chmod 777 ./UI/deploy.sh
    - name: Deploy to ec2
      uses: appleboy/ssh-action@master
      env:
        USERNAME: ec2-user
        HOST: ec2-34-229-232-99.compute-1.amazonaws.com
        SCRIPT: ~/deploy.sh
        KEY: ${{ secrets.SSH_DEPLOYMENT_KEY }}    
