# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - run: npm install  --prefix ./UI
    - run: npm run build --prefix ./UI

      
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:
         name: build
         path: ./UI/dist

    - uses: actions/download-artifact@master
    - name: Build Docker container1
      run: docker build -t prasanna002/nodenginx --file ./UI/Dockerfile .
    - run: docker login -u prasanna002 -p Muthala@123P         
    - run: docker push prasanna002/nodenginx
      
  
    - name: Executing remote  command
      uses: appleboy/ssh-action@master
      with:
          host: ec2-35-168-13-144.compute-1.amazonaws.com
          USERNAME: ec2-user
          PORT: 22
          KEY: ${{ secrets.SSH_DEPLOYMENT_KEY }}
          script: sudo systemctl start docker && docker run -itd --rm --privileged -p 8081:80 --name node-UI prasanna002/nodenginx
 
